In [4]:
import numpy as np

### Compute the Linear Discriminant projection for the following two-dimensional dataset:

In [39]:
X1 = np.array([
    [4, 1],
    [2, 4],
    [2, 3],
    [3, 6],
    [4, 4]
])
X2 = np.array([
    [9, 10],
    [6, 8],
    [9, 5],
    [8, 7],
    [10, 8]
])

In [43]:
# Calculate within-class and between-class scatter matrixes

u1 = np.mean(X1, axis=0)
u2 = np.mean(X2, axis=0)

In [41]:
S1 = (X1-u1).T.dot((X1-u1))/X1.shape[0]
S2 = (X2-u2).T.dot((X2-u2))/X2.shape[0]

In [42]:
SW = S1 + S2 # within-class scatter matrix
SW

array([[ 2.64, -0.44],
       [-0.44,  5.28]])

In [71]:
ud = (u1-u2)[:, np.newaxis]
SB = ud.dot(ud.T)
SB

array([[29.16, 21.6 ],
       [21.6 , 16.  ]])

In [82]:
# Solve generalized eigenvalue problem

evals, evecs = np.linalg.eig(np.linalg.inv(SW).dot(SB))

In [83]:
evecs

array([[ 0.91955932, -0.59522755],
       [ 0.39295122,  0.80355719]])